language: node_js
node_js:
  - "stable"
dist: focal
before_install:
  - gem install bundler

before_deploy:
  - yes | gem update --system --force
  - gem install uri
  - gem install logger
  - gem install faraday-net_http -v '3.3.0'
deploy:
  provider: pages
  cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main