language: node_js
node_js:
  - "stable"
dist: focal
before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger
deploy:
  provider: pages
  cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
